server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  data:
    mongodb:
      host: 192.168.1.252
      port: 27017
      database: swagger_diff
      auto-index-creation: true
